services:
  rest-producer-app:
    container_name: rest-producer-app
    build:
      context: ./producer-app/rest-producer
    ports:
      - "8060:8060"
    environment:
      CONSUMER_ENDPOINT_URL: http://rest-consumer-app:8070/consumes
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 128m
    networks:
      - rest-network
    depends_on:
      - rest-consumer-app

  rest-consumer-app:
    container_name: rest-consumer-app
    build:
      context: ./consumer-app/rest-consumer
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 90m
    networks:
      - rest-network

networks:
  rest-network:
    driver: bridge